### ISSUE TITLE
Problema com botão

### ISSUE THREAD

**Issue by thomasce10** [NOEIFCE/GalaxyEscape#1]
onButtonClick : function()
    {
        this.massa = this.massaText.string.parseInt();
        this.massa += 1;
        this.massaText.string = this.massa.toString();
    }

#this.massa inicial não está recebendo o valor inteiro da string do label "massaText"
porém ao removê-lo o valor da string é alterado

**Comment by johnsonpeixoto** [comment]
Assim, **massaText** tá lá em _properties_, mas onde tu declarou **massa** que tu usa em `this.massa = this.massaText.string.parseInt();` ?

**Comment by thomasce10** [comment]
foi vacilo mesmo não era isso, é que eu estava tentando pegar a string do massaLabel dentro da função, quando não era necessário já que o valor de captura já se altera.
